apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: test-app-route
  namespace: ${namespace}
spec:
  parentRefs:
    - name: ${gateway_name}
      namespace: ${gateway_namespace}
  hostnames:
%{ for hostname in hostnames ~}
    - ${hostname}
%{ endfor ~}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: test-app-service
          port: 8080
          weight: 1
